homepage = "https://github.com/crate-ci/typos"
urlInMirror = "v${version.main}/typos-v${version.main}-${architecture}-unknown-linux-musl.tar.gz"
mirrors = ["https://github.com/crate-ci/typos/releases/download"]
compression = ".tar.gz"

[version]
main = "1.39.0"

[architectureNames]
amd64 = "x86_64"

[checksums]
"v1.36.2/typos-v1.36.2-x86_64-unknown-linux-musl.tar.gz" = "d255f509aca7d43a50854cdc5ea94480b13918459992e3b5f2d0d8c4eadddb49"
"v1.39.0/typos-v1.39.0-x86_64-unknown-linux-musl.tar.gz" = "f8ca3734d24b5727ac7f963528e53760dbca2f24f3318a4b80c5db1b7d0bf5b9"
